services:
  backend:
    build: ./backend
    restart: always 
    env_file:
      - ./backend/.env
    ports:
      - "3000:5000"
    volumes:
      - ./backend:/usr/src/app
      - /usr/src/app/node_modules
    
  
  frontend:
    build:
      context: ./frontend
    restart: always 
    ports:
      - 5173:5173
    depends_on:
      - backend
    
      

